services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=database
      - DB_NAME=social_db
      - DB_USER=social_admin
      - DB_PASS=admin

    depends_on:
      - database


  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=social_db
      - POSTGRES_USER=social_admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis


